site_name: Web Security Using Django
site_description: Comprehensive documentation on web security using Django
site_author: Domenez25
site_url: https://github.com/Domenez25/secure-web-application-using-django

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: "indigo"
      accent: "indigo"
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: "indigo"
      accent: "indigo"
  font:
    text: "Roboto"
    code: "Roboto Mono"
  logo: "images/logo.png"
  favicon: "images/favicon.ico"
  features:
    # - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
    # - toc.integrate
    - content.code.annotate
    - content.tabs.link
    - navigation.expand
    # - navigation.sections
    - search.share
    - content.code.copy

nav:
  - Home: index.md
  - Introduction: introduction.md
  - Core Concepts:
      - Overview of Security: core-concepts/security.md
      - Overview of Web applications: core-concepts/web apps.md
      - Overview of Web Security Threats: core-concepts/overview.md
      - Importance of Security in Web Development: core-concepts/importance.md
  - Django Security Features:
      - SQL Injection Protection: django-security/sql-injection.md
      - Cross-Site Scripting (XSS) Protection: django-security/xss.md
      - Cross-Site Request Forgery (CSRF) Protection: django-security/csrf.md
      - Secure Password Storage: django-security/password-storage.md
      - HTTPS Support: django-security/https.md
      - Content Security Policy (CSP): django-security/csp.md
      - Logging: django-security/logging.md
      - Security misconfigurations: django-security/misconfiguration.md
  - Best Practices:
      - General Security Practices: best-practices/general-security-practices.md
      - Secure Coding Practices: best-practices/secure-coding-practices.md
      - authentication authorization: best-practices/authentication-authorization.md
      - dataprotection: best-practices/data-protection.md
      - configuration deployment: best-practices/configuration-deployment.md
      - network security: best-practices/network-security.md
      - monitoring logging: best-practices/monitoring-logging.md
      - third party dependencies: best-practices/third-party-dependencies.md
      - performance scalability: best-practices/performance-scalability.md
      - user education awareness: best-practices/user-education-awareness.md
      - compliance legal: best-practices/compliance-legal.md
  - Advanced Techniques:
      - custom middleware security: advanced-techniques/custom-middleware-security.md
      - advanced authentication: advanced-techniques/advanced-authentication.md
      - rbac: advanced-techniques/rbac.md
      - Rate Limiting and Throttling: advanced-techniques/Rate-Limiting-and-Throttling.md
      - API Security: advanced-techniques/API-Security.md
      - Advanced Logging and Monitoring: advanced-techniques/Advanced-Logging-and-Monitoring.md
      - SIEM: advanced-techniques/SIEM.md
  - Case Studies: case-studies.md
  - Additional Resources: resources.md
  - About the Author: author.md

plugins:
  - search
  - i18n:
      languages:
        en: English
        fr: Français
      default_language: en

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.details
